### ISSUE TITLE
Using cassandra::optutils will upgrade cassandra to 3.x

### ISSUE THREAD

**Issue by mbugeia** [locp/cassandra#187]
Hi,
When using the class cassandra::optutils there is no way to specify the package version to install. In fact using the class will upgrade cassandra to the last version available of cassandra-tools (at least on ubuntu).
We need something like this:
```
class { 'cassandra::optutils':
  package_ensure => $version,
}
```

**Comment by dallinb** [comment]
Hi @mbugeia,

Please see existing `ensure` attribute https://github.com/locp/cassandra#class-cassandraoptutils which provides what you want.  Therefore you could have the following:

```puppet
$version = '2.2.4'

class { 'cassandra':
  package_ensure => $version,
} ->
class { 'cassandra::optutils':
  ensure => $version,
}
```

It doesn't quite follow the same naming convention (maybe it should also been called `package_ensure` for consistency).

Does this answer your question?

**Comment by mbugeia** [comment]
Thank you ! Yes it does answer my question, I did skip the "or a version number" part of the doc. And yes  I think too that package_ensure would be better for consistency.

**Comment by dallinb** [comment]
Hi,

I've raised #188 to address this.

Thanks for the feedback.
