### ISSUE TITLE
Missing attributes in cassandra.yaml

### ISSUE THREAD

**Issue by samyray** [locp/cassandra#217]
In new cassandra versions there are few new attributes in cassandra.yaml, so it would be cool to add them to module as well:

- memtable_allocation_type

```
(Default: heap_buffers) Specify the way Cassandra allocates and manages memtable memory. See Off-heap memtables in Cassandra 2.1. Options are:
heap_buffers
On heap NIO (non-blocking I/O) buffers.

offheap_buffers
Off heap (direct) NIO buffers.

offheap_objects
Native memory, eliminating NIO buffer heap overhead.
```

- compaction_large_partition_warning_threshold_mb

`(Default: 100) Logs a warning when compaction partitions larger than the set value.`

**Comment by dallinb** [comment]
Thanks for the suggestions (especially the undocumented compaction_large_partition_warning_threshold_mb).  Will be released in version 1.20.0 (see #219).
