### ISSUE TITLE
Add ability to manipulate environment file

### ISSUE THREAD

**Issue by dallinb** [locp/cassandra#218]
There should be the ability (probaly via Augeas) to set, alter and remove lines in the Cassandra environment file.

**Comment by tibers** [comment]
What specifically did you envision for this? I'm sort of concerned because our original plan was to make a giant heap and see if it improved performance on a giant dataset and I'll be the first to say we royally screwed up. :)

**Comment by dallinb** [comment]
Hi Joshua,

I plan it to be a convenience function to do exactly what you suggest (tuning of MAX_HEAP). If you have plenty of time, see  *Revaluate Default JVM tuning parameters* (available at https://issues.apache.org/jira/browse/CASSANDRA-8150) which also includes links to *Migrate to G1GC by default* (https://issues.apache.org/jira/browse/CASSANDRA-7486).
