### ISSUE TITLE
GRANT/REVOKE

### ISSUE THREAD

**Issue by dallinb** [locp/cassandra#222]
http://docs.datastax.com/en/cql/3.0/cql/cql_reference/grant_r.html
http://docs.datastax.com/en/cql/3.0/cql/cql_reference/revoke_r.html

- [x] Unit tests
- [x] Acceptance Tests
- [x] Example manifests
- [x] Example inline documentation.

**Comment by tibers** [comment]
I'm following the project now - is there an outstanding wishlist somewhere you folks want help with?

**Comment by dallinb** [comment]
Hi Joshua,

Thank you very much for the offer.  Seeing as you have been carrying out some testing on Cassandra 3 (#189) would it be possible for you to look at #223 so that we can automatically test against version 3 of Cassandra on all supported operating systems?

Best wishes,

Ben
