### ISSUE TITLE
Java version installed on Debian family by cassandra::java class

### ISSUE THREAD

**Issue by dallinb** [locp/cassandra#223]
Currently the Debian family of operating systems installs the default openjdk version 7.  This means that Cassandra 3 refuses to run.  For this reason, lines 530 - 604 have been commented out in spec/acceptance/cassandra_spec.rb (there was also a problem with the hints directory but this was resolved by @tibers in 1.15.0/#189).  What is needed is for the cassandra::java class to install a Java runtime that is supported by Cassandra 3.X.

Definition of done:

With lines 530 - 604 active in  spec/acceptance/cassandra_spec.rb the following command completes successfully:

`BEAKER_set=circle_ubuntu14 bundle exec rake beaker`

It is currently failing with:

> Error: /Stage[main]/Cassandra/Service[cassandra]/ensure: change from stopped to running failed: Could not start Service[cassandra]: Execution of '/etc/init.d/cassandra start' returned 1: Cassandra 3.0 and later require Java 8u40 or later.

**Comment by tibers** [comment]
I think I have it, but I'm having problems satisfying the spec. [Here's the logs.](https://circleci.com/gh/locp/cassandra/681) I am looking for suggestions.

**Comment by dallinb** [comment]
Taking a look now and will put comments in the change request.  At first glance the new code looks good.  Thank you so much for taking the time to do this.
