### ISSUE TITLE
Missing Coverage on cassandra::env

### ISSUE THREAD

**Issue by dallinb** [locp/cassandra#230]
https://coveralls.io/jobs/13898023/source_files/318281343

**Comment by tibers** [comment]
This actually looks pretty swank. I read the ruby/rails docs - how much of this is generated?

**Comment by dallinb** [comment]
I wish it was generated automatically but no it's all written by hand.  Realized that I had thousands of lines of Ruby code for the test harnesses and that probably it was important to have that standardized which is when I added Rubocop to the unit tests.  So I now have tests for the tests.  To be honest ensuring that the coverage is at 100% (as shown in Colveralls) has saved my backside on many occasion.  Doing the couple of lines change to the code and then having "bundle exec rake spec" throwing a subsequent errors has provided the "Oh, yeah!" moment of reflection on a number of occasions.

See http://rspec-puppet.com/ for more detailed documentation on it.
