### ISSUE TITLE
module tries to start cassandra before it's installed

### ISSUE THREAD

**Issue by tibers** [locp/cassandra#232]
Nice to have: don't try to start cassandra before it's installed.

```
Error: Could not start Service[cassandra]: Execution of '/sbin/service cassandra start' returned 1: cassandra: unrecognized service
Error: /Stage[main]/Cassandra/Service[cassandra]/ensure: change from stopped to running failed: Could not start Service[cassandra]: Execution of '/sbin/service cassandra start' returned 1: cassandra: unrecognized service
```

**Comment by dallinb** [comment]
Hi,

What are you setting the `package_ensure` and `service_refresh` attributes to?

Best wishes,

Ben

**Comment by tibers** [comment]
https://github.com/locp/cassandra/pull/233

We do set `cassandra::service_enable: true` and `cassandra::service_refresh: false`. `package_ensure` is set to a specific version string.

I just tested this on a dev box we had around and it seems to be doing The Right Thing now.

**Comment by dallinb** [comment]
OK, going with your pull request as it is a more complete solution.  When I wrote the original code I guess I forgot about require while being paranoid about avoiding notify or subscribe.  You've also put in the full requirements.  Thank you again.
