### ISSUE TITLE
cassandra.service systemctl @ active (exited)

### ISSUE THREAD

**Issue by jaguth** [locp/cassandra#24]
I'm running Centos 7 (puppetlabs/centos-7.0-64-puppet) thats running via freshly provisioned vagrant and virtual box. I provisioned my puppet file as:
class { 'cassandra':
  cluster_name                 => 'Foobar Cluster',
  listen_address               => "0.0.0.0",
  seeds                        => "0.0.0.0",
  cassandra_opt_package_ensure => 'present',
  java_package_name            => 'java-1.7.0-openjdk',
  java_package_ensure          => 'present',
  manage_dsc_repo              => true
}

Cassandra provisions without errors.  However, its stuck in active (exited);
[vagrant@hydrabox ~]$ systemctl status cassandra.service
cassandra.service - SYSV: Starts and stops Cassandra
   Loaded: loaded (/etc/rc.d/init.d/cassandra)
   Active: active (exited) since Thu 2015-07-02 16:55:53 UTC; 5min ago

How can i get it so that its active (running)?

Thank you in advance!

**Comment by jaguth** [comment]
I discovered from less /var/log/cassandra/cassandra.log that cassandra sees "0.0.0.0" as a wildcard and will not allow it for the listen addess or seeds.  It wants an empty string for localhost, so i set them to "", destroyed my vagrant vm, and up'ed a new vm.  Now less /var/log/cassandra/cassandra.log does not contain any errors, but still its stuck in active (exited) 8(

**Comment by dallinb** [comment]
Hi,

Will look at this ASAP and get a release 0.3.1 out as soon as possible.

**Comment by dallinb** [comment]
@jaguth If this is a single node, then you could leave the listening and seed addresses to be the default.  Obviously not much good in a cluster.  In which case can you specify the exact addresses for the node?  The seed cannot be blank as any node (including a standalone node) will not know how to obtain it's initial information about the cluster when attempting to join.

**Comment by dallinb** [comment]
@jaguth if you wanted the listen address and seed addresses to default to localhost, you would set the manifest to something like this:

```puppet
class { 'cassandra':
  cluster_name                 => 'Foobar Cluster',
  cassandra_opt_package_ensure => 'present',
  java_package_name            => 'java-1.7.0-openjdk',
  java_package_ensure          => 'present',
  manage_dsc_repo              => true
}
```

This can be confirmed by then seeing that the settings are correct in the configuration file:

```bash
# grep -e "^listen" -e "- seeds" /etc/cassandra/default.conf/cassandra.yaml
          - seeds: "127.0.0.1"
listen_address: localhost
```

These settings work fine for me on a test node running the same operating system as you are.  I configured the node to have 1 vCPU and 1GB of RAM.

Would it be possible to set your manifest to be the same and to then let me know the outcome?  If it is still failing, please can you send me:

* Your manifest
* A copy of the cassandra log files (**/var/log/cassandra/***)

The example at the beginning of the usage section of the README is working code and is a bit more realistic an example of how a cluster should be created.

Best wishes,

Ben

**Comment by jaguth** [comment]
Hi  dallinb, thank you very much for your quick response.  The following does indeed work on a single node 1 vCPU and 1GB of RAM:
class { 'cassandra':
  cluster_name                 => 'Foobar Cluster',
  cassandra_opt_package_ensure => 'present',
  java_package_name            => 'java-1.7.0-openjdk',
  java_package_ensure          => 'present',
  manage_dsc_repo              => true
}

and the grep command does indeed return the same output you have.  However, the service still shows as "active (exited)" and i am unable to connect to it with cqlsh:

[vagrant@hydrabox ~]$ cqlsh
Connection error: ('Unable to connect to any servers', {'127.0.0.1': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})

Here is my vagrantfile:
### how to test connection once vagrant vm is up ###
# couchbase: http://localhost:8091
# elasticsearch: http://localhost:9200
# redis:
# cassandra: 

### settings ###
box_name = "puppetlabs/centos-7.0-64-puppet"
centos_download_uri = "puppetlabs/centos-7.0-64-puppet"
num_ram = 1024
num_cpus = 1
default_bridge = "en0"
public_ip = "192.168.20.2"
vpn = "off"
vm_name = "hydrabox" # because multiple heads for multiple datastores

### implementation ###
Vagrant.configure("2") do |config|

  # Define virtualbox settings
  config.vm.provider :virtualbox do |vb|
    vb.name = vm_name
    #vb.memory = num_ram #disabled
    vb.cpus = num_cpus
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "#{vpn}"]
  end
  
  # Define libvert settings
  config.vm.provider :libvirt do |libvirt|
    #libvirt.memory = num_ram #disabled
    libvirt.cpus = num_cpus
  end
  
  # Define the vagrant box download location
  config.vm.box_url = centos_download_uri

  # Provision the server with puppet
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "./"
    puppet.manifest_file = "puppet.pp"
    puppet.module_path = "~/.puppetlabs/etc/code/modules"
  end
  
  # Provision Config
  config.vm.box = box_name
  config.vm.hostname = vm_name
  config.vm.network "private_network", ip: public_ip
  config.vm.network :forwarded_port, host: 9160, guest: 9160 #cassandra
  config.vm.network :forwarded_port, host: 9042, guest: 9042 #cassandra

end

Here is my puppet.pp file:
# Ensure firewall is off
service { "firewalld.service":
  ensure => "stopped"
}

### CASSANDRA ###
class { 'cassandra':
  cluster_name                 => 'Foobar Cluster',
  cassandra_opt_package_ensure => 'present',
  java_package_name            => 'java-1.7.0-openjdk',
  java_package_ensure          => 'present',
  manage_dsc_repo              => true
}

**Comment by dallinb** [comment]
Oh good heavens.  I've just realised that the nodesets I use have 2GB of RAM (see the files under **./spec/acceptance/nodesets** specifically **centos-7-x64.yml**).  I'm going to check this out on 1GB and see if I can recreate the problem to confirm.

**Comment by dallinb** [comment]
OK.  Indeed, that is the problem.  1GB of RAM is not enough.  My attempts to run ```nodetool status``` and ```cqlsh``` both failed as the service was not running correctly.  There is nothing in the log files, but at the tail end of the output of ```dmesg``` is the following message:

```
[  293.954922] Out of memory: Kill process 4281 (java) score 438 or sacrifice child
[  293.957323] Killed process 4281 (java) total-vm:1192244kB, anon-rss:799116kB, file-rss:119992kB
```

When I revert the the RAM to 2GB, all is OK.  Really sorry for the duff information that I gave in the comment last night.  Would you be able to confirm if all is OK when you up the RAM as well?

**Comment by jaguth** [comment]
That worked!  Bumping my VM's RAM up to 2GB worked!  Thank you so much!

**Comment by dallinb** [comment]
Hi,

Thank you for the feedback and for your patience.  One of the outcomes of this issue is that more tests have been put in place while I was working on this and these will be in future releases.

Thanks again,

Ben

**Comment by emeraldhieu** [comment]
I got the same issue on AWS EC2 t2.micro (1GB RAM). The log didn't show any error. Changing instance type fixed the issue. Thanks for the useful answer.
