### ISSUE TITLE
upgraded to locp-cassandra (v1.24.0), nodes running cassandra but not defined in foreman were updated/modified.

### ISSUE THREAD

**Issue by aurbain** [locp/cassandra#250]
Hi,

I have two cassandra clusters in my dev environment.  Cassandra[1,2,3] and cassandra[11,12,13].  The former has no cassandra class defined.

Some hours after upgrading to locp-cassandra (v1.24.0) from (v1.23.0), Cassandra[1,2,3] nodes were modified.

Not sure how that could happen.
I can provide logs as desired.
Foreman Version: 1.9.3-1, ubuntu 1404.

root@puppet:/var/log/foreman# cat  /etc/apt/sources.list.d/foreman.list
deb http://deb.theforeman.org/ trusty 1.9
deb http://deb.theforeman.org/ plugins 1.9

Please advise.

-Aaron.

**Comment by dallinb** [comment]
Hi Aaron,

Just to clarify, the nodes had already been built against locp-cassandra 1.23.0, you upgraded the version of locp-cassandra to 1.24.0 and this executed code?  If that is the case and you want to find out why there was a change, please can you send me the logs.  It will probably tomorrow that I look at it because it is 6.20 PM here.

**Comment by aurbain** [comment]
Ben,
The nodes which changed were built by hand and not by locp-cassandra.  This older cluster (cassandra1=usergrid, cassandra2, cassandra3) only had puppet managing OS things, like /etc/hosts, apt, ntpd, etc.  No cassandra class was defined.

**Comment by dallinb** [comment]
I'll probably need to see logs. I'll also admit that my knowledge of foreman is very limited.

**Comment by tibers** [comment]
Foreman does the same thing most of these tools do where if you define your
groups with a regex and it matches to anything with cassandra in it, you
get them all lumped together. Did you check your foreman configuration?

**Comment by aurbain** [comment]
That makes sense, however I don't use regexes to assign classes via, for example, hostname; I assign classes to hosts using the node->edit->classes page in foreman.

**Comment by dallinb** [comment]
I can't think of anything within this module (on indeed any module) that would make it get executed when the class had not been declared.  Is this not more a question about Foreman?

**Comment by dallinb** [comment]
Hi,

Do you have any more information on this?  Is there anything more obvious in the logs?  If so can you put them into this issue?

Best wishes,

Ben

**Comment by aurbain** [comment]
I agree with dallinb, this is better addressed on a Foreman forum.
Closing.
