### ISSUE TITLE
Datastax 5 supported?

### ISSUE THREAD

**Issue by peske** [locp/cassandra#259]
I just want to check if Datastax Enterprise version 5 is supported.

(As far as I know Datastax introduced a lot of changes in this version, so it's better to ask...)

Thanks!

**Comment by dallinb** [comment]
Hi @peske, 

We have been doing test builds as part of our release process against Cassandra 3.0 for some time now.  According to http://docs.datastax.com/en/landing_page/doc/landing_page/compatibility.html that is one of the components of DataStax Enterprise 5.0.  I have not personally had an opportunity to try out version 5.0 as it has not been a client requirement yet.

Currently I'm working on what will be version 2.0.0 of this module which provides a more flexible API although I am pretty sure the the current version should be OK.  Please try with the current version and if you do experience any problems (we found setting the `hints_directory` was required for Cassandra 3.X) please raise them here.

Best wishes,

Ben

PS

I will automatically close this call after a week if I hear nothing from you, but please also feel free to keep the discussion going.

**Comment by peske** [comment]
Thanks for the answer Ben!

I've tried and succeeded to install 5 node cluster by using your module. Let me share my experience:

1. You were right about setting `hints_directory` - without it Cassandra will try to create `/hints' folder and fail.
2. I've had to add the following:

```
limits::fragment {
 "root/-/memlock":
   value => "unlimited";
 "root/-/nofile":
   value => "100000";
 "root/-/nproc":
   value => "32768";
 "root/-/as":
   value => "unlimited";
}
```

It looks that the same limits added by the package (defined for user `cassandra`) are not enough. I'll check later under which user the service runs and let you know.

Thanks again!

**Comment by dallinb** [comment]
@peske ,

Thank you very much for the feedback.  The `hints_directory` was thanks to the investigation and (gratefully received) PR by @tibers .

Best wishes,

Ben

**Comment by dallinb** [comment]
Hi,

Do you feel that your question has been answered?  In which case could you close this issue?

Best wishes!

**Comment by dallinb** [comment]
@peske 

Closing this case for now.  If you feel this has not fully answered your question so far, please re-open this issue.

Best wishes,

Ben
