### ISSUE TITLE
Unit cassandra.service failed to load: No such file or directory.

### ISSUE THREAD

**Issue by electromecca** [locp/cassandra#260]
Error:
Error: Could not start Service[cassandra]: Execution of '/usr/bin/systemctl start cassandra' returned 6: Failed to start cassandra.service: Unit cassandra.service failed to load: No such file or directory.
Wrapped exception:
Execution of '/usr/bin/systemctl start cassandra' returned 6: Failed to start cassandra.service: Unit cassandra.service failed to load: No such file or directory.
Error: /Stage[main]/Cassandra/Service[cassandra]/ensure: change from stopped to running failed: Could not start Service[cassandra]: Execution of '/usr/bin/systemctl start cassandra' returned 6: Failed to start cassandra.service: Unit cassandra.service failed to load: No such file or directory.

config:
cassandra::seeds: '10.193.27.24,10.193.27.25,10.193.27.26,10.193.27.27,10.193.27.28,10.193.27.29'
cassandra::cluster_name: "Load cluster"
cassandra::config_path: "/apps/ctp/cassandra/conf"

os Centos7

**Comment by dallinb** [comment]
Hi,

Which version of Cassandra are you installing and are you setting `service_systemd` to true?

Best wishes,

Ben

**Comment by electromecca** [comment]
Hi there, 
I was setting that to true but then I read its set by default for centos7? Either way it was not working. Got around it by setting profile for cassandra.

cqlsh> select release_version from system.local;

 release_version
-----------------
           2.2.6

Best Regards,
Bart

**Comment by dallinb** [comment]
Hi,

Currently, the default for `service_systemd` (see https://github.com/locp/cassandra#service_systemd) the functionality to make it default to `true` for CentOS 7 is scheduled for version 2.0.0 of this module (to be released shortly).  However, I'm having second thoughts about that as Cassandra 3.X seems to provide a working unit file.

If this answers your question, is it OK for the issue to be closed?

**Comment by electromecca** [comment]
thanks, but I was getting this issue either with systemd set to true or not. So just flagging that it might not work as expected. I have a work around for now but I will keep an eye on updates.
Thanks

**Comment by tibers** [comment]
> However, I'm having second thoughts about that as Cassandra 3.X seems to provide a working unit file.

Gentle thread hijacking: I'd like to assume that the newest stuff is the least hacky stuff, and then the hacky stuff can get progressively worse for old versions. So if cassandra 3 provides the functionality in the package we need, just make the older versions hacky. It'll eventually sort itself out as cassandra versions go EOL and hacky crap can be deprecated. Right?
