### ISSUE TITLE
PID file name in systemd file for datastax-agent doesn't match PID file name in /etc/init.d/datastax-agent

### ISSUE THREAD

**Issue by pampelix** [locp/cassandra#264]
In /etc/init.d/datastax-agent: 
NAME="datastax-agent"
PID="/var/run/$NAME/$NAME.pid"

in /usr/lib/systemd/system/datastax-agent.service: 
PIDFile=/var/run/datastax-agent/datastax-agent-monitor.pid

This causes datastax-agent not to run on systemd enabled systems.

fix: 
--- a/templates/datastax-agent.service.erb
+++ b/templates/datastax-agent.service.erb
@@ -5,7 +5,7 @@ Description=DataStax Agent
 After=network.target
 
 [Service]
-PIDFile=/var/run/<%= @service_name %>/<%= @service_name %>-monitor.pid
+PIDFile=/var/run/<%= @service_name %>/<%= @service_name %>.pid
 ExecStart=/etc/init.d/<%= @service_name %> start
 StandardOutput=journal
 StandardError=journal

thanks :)

**Comment by dallinb** [comment]
Hi,

This has worked OK on CentOS 7 which is systemd enabled.  Which OS/Release are you using.  Regardless though, you are right to say that the name should be made consistent with the service so I'll get a patch sorted out.

Ben

**Comment by pampelix** [comment]
I'm on RHEL7, trying to start the service didn't do anything at all, not even log output. took me a while to find the issue, I created a fork for locp/cassandra with the above fix and it all worked smoothly.

**Comment by dallinb** [comment]
Hi, that's the change in the latest (1.25.1) release of the module.  Just one more quest, what version of the DataStax Agent are you running with?

**Comment by pampelix** [comment]
Hi,

That issue occured with latest version, 6.0.1

Cheers for fixing! :)
