### ISSUE TITLE
recommended production settings

### ISSUE THREAD

**Issue by stanleyz** [locp/cassandra#267]
The module probably should follow the below link to set up recommended production settings, I am using my profile to do so at the moment, and I am happy to help if you don't mind, but not at the moment, too busy.

https://docs.datastax.com/en/cassandra/2.0/cassandra/install/installRecommendSettings.html
https://docs.datastax.com/en/cassandra/2.2/cassandra/install/installRecommendSettings.html
http://docs.datastax.com/en/landing_page/doc/landing_page/recommendedSettingsLinux.html

Can't run the acceptance tests for sysctl as our Beaker tests run in Docker.  Therefore have to run tests manually via Vagrant:

- [x] rake beaker:aws_centos6
- [x] rake beaker:aws_centos7
- [x] rake beaker:aws_debian8
- [x] rake beaker:aws_ubuntu12
- [x] rake beaker:aws_ubuntu14
- [x] rake beaker:aws_ubuntu16
- [x] rake beaker:circle_debian7

**Comment by dallinb** [comment]
@stanleyz I've been thinking of putting something in to do this already.  I'll do the work after 2.0 has been released (see https://github.com/locp/cassandra/tree/release/major for progress on this so far).

**Comment by dallinb** [comment]
Disable swap notes https://groups.google.com/forum/#!topic/puppet-users/bqeM0h6zyGQ

**Comment by dallinb** [comment]
A lot of this was released in 2.3.0 of the module.  Leaving the rest for now as it was specific to disk types.
