### ISSUE TITLE
should the default service_ensure to be undef?

### ISSUE THREAD

**Issue by stanleyz** [locp/cassandra#268]
Some user like us don't want Puppet to manage the service status for some applications such as C*, the reason is simply that it would bring more work if one node accidentally joins a production cluster, setting the default service_ensure to undef gives user the control whether Puppet should manage the service status or not.

**Comment by tibers** [comment]
It's the default, common pattern to have puppet manage the service. How else is the service going to notice changes to the configuration?

**Comment by stanleyz** [comment]
Surely this topic is debatable, I understand it's not usual to manage service this way in Puppet, but for distributed applications such as Cassandra, Elasticsearch etc, I think it's acceptable because one typo in configurations could cause the whole cluster contaminated, people like us tends to more careful on restarting such applications.

Besides what I requested is to make the default value to **undef**, users who do want to manage service status in Puppet can still set it to true. But the if the default value is true, you have no way to set it to **undef** due to the inability of Puppet to pass **undef**.

**Comment by dallinb** [comment]
Let me think about this one.  Currently leaning towards setting the default to `undef` but want to try some testing on this before committing to anything.  Also this would be an API changing modification (according to [SemVer](http://semver.org/)) so it will need to go into release 2.0.0 which is scheduled for a couple of weeks.

**Comment by dallinb** [comment]
I just want to confirm this feature is not covered by the `service_refresh` attribute?  This is the blurb from the README:

> If set to true, changes to the Cassandra config file or the data directories will ensure that Cassandra service is refreshed after the changes. Setting this flag to false will disable this behaviour, therefore allowing the changes to be made but allow the user to control when the service is restarted. Default value true

This attribute was added as part of #119 and released in version 1.8.0.

**Comment by dallinb** [comment]
@stanleyz If this were to be implemented then it would be an increment to the major release number (as it is a fundamental change to the API).  I am hoping to release 2.0.0 early next week so would it be possible for you to reply ASAP?  If you think that the `service_refresh` attribute protects you from this risk please also let me know.

**Comment by stanleyz** [comment]
@dallinb no, service_refresh doesn't cover service_ensure. 

Setting service_refresh to false will let Puppet not restarting Cassandra if any configuration files get changed, but service_ensure will make sure the process is running/stopped even if you don't have a change to any configuration files. It's basically the difference between refresh and ensure explained here:

**Comment by stanleyz** [comment]
Thanks for changing that by the way @dallinb ,  sorry that I didn't reply back earlier, was too busy in the last few days.

**Comment by dallinb** [comment]
@stanleyz No worries, I'll put it in.

**Comment by dallinb** [comment]
Incorrectly attributed commit 703cc71  to issue #258 when the comment should have been for this issue.

**Comment by dallinb** [comment]
@stanleyz Please can you take a look at https://github.com/locp/cassandra/compare/improvement/272/documentation...improvement/268/service_ensure

Tested on CentOS 7.

**Comment by stanleyz** [comment]
looks great to me @dallinb thanks.
