### ISSUE TITLE
Ubuntu 16 doesnt like the service file

### ISSUE THREAD

**Issue by ahharu** [locp/cassandra#269]
We get /usr/bin/kill and /usr/bin/rm not found. Even if we change this to /bin/kill and /bin/rm service won't start

**Comment by ahharu** [comment]
We are using cassandra 2.2.4 on Ubuntu 16.04 . I have switched this to false and it starts without bombing :)

**Comment by dallinb** [comment]
Cool thanks for letting me know.  I may well create a patch version that adds more documentation with regards to the `service_systemd` flag.  See #243 for details of what is happening on the Red Hat family.  Are you happy enough for this issue to be closed for now?

**Comment by ahharu** [comment]
That makes sense, I can live with it set to false

**Comment by dallinb** [comment]
I'll keep this open for now as a reminder to update the documentation.

**Comment by dallinb** [comment]
Actually, I think I found a way of removing this flag all together.  Testing in progress.
