### ISSUE TITLE
Add ability to specifie the seed nodes as array

### ISSUE THREAD

**Issue by Mortinke** [locp/cassandra#278]
Could we create the possibility that the seed nodes can be specified as array?
We would use the _seed_-variable in other modules e.g. the monitoring module [jmxtrans](https://github.com/jmxtrans/jmxtrans). 
It would be nice if we can loop through this value instead use string functions to extract each ip address.

**Comment by dallinb** [comment]
Released to Puppet Forge https://forge.puppet.com/locp/cassandra/1.26.0/changelog
