### ISSUE TITLE
Beaker Acceptance Tests Blocking 2.0.0

### ISSUE THREAD

**Issue by dallinb** [locp/cassandra#281]
- [x] aws_centos6: FAILED (https://travis-ci.org/locp/cassandra/jobs/159931277)
- [x] aws_ubuntu12: FAILED (https://travis-ci.org/locp/cassandra/jobs/159931277)
- [x] aws_ubuntu14: FAILED (https://travis-ci.org/locp/cassandra/jobs/159931278)

CentOS 7, the Debians and Ubuntu 16 are all fine.

This issue is blocking #274.

**Comment by dallinb** [comment]
Seem to be a victim of https://github.com/pcfens/puppet-filebeat/issues/20

**Comment by dallinb** [comment]
Ubuntu 12 is still failing.  Needs more investigating.  It is failing attempting to connect to Cassandra.  This is strange as I can login to the docker container and run `/usr/bin/cqlsh -u cassandra -p cassandra  -e 'DESC KEYSPACES' 172.17.0.2 9042` without any issue.

**Comment by tibers** [comment]
Well, Ubuntu 12 is only supported through April or something... :)

**Comment by dallinb** [comment]
Also had problems with termansi-color on Travis.

https://travis-ci.org/locp/cassandra/jobs/163215549

**Comment by dallinb** [comment]
Now having problems with Travis running beaker.  Comparing ruby versions since when this actually fired stuff up:

```shell
12:39 $ diff beaker.runs.bundle.txt beaker.not_running.bundle.txt 
18,19c18,19
< Installing ethon 0.9.0
< Installing excon 0.52.0
---
> Installing ethon 0.9.1
> Installing excon 0.53.0
27c27
< Installing fog-aws 0.11.0
---
> Installing fog-aws 0.12.0
29c29
< Installing fog-core 1.42.0
---
> Installing fog-core 1.43.0
36c36
< Installing fog-profitbricks 0.0.5
---
> Installing fog-profitbricks 2.0.1
62c62
< Installing jwt 1.5.4
---
> Installing jwt 1.5.6
72c72
< Installing minitest 5.9.0
---
> Installing minitest 5.9.1
85c85
< Installing parser 2.3.1.2
---
> Installing parser 2.3.1.4
97c97
< Installing rbvmomi 1.9.2
---
> Installing rbvmomi 1.9.3
```
