### ISSUE TITLE
locp/cassandra 2.0 example has two cassandra declarations

### ISSUE THREAD

**Issue by ericy-jana** [locp/cassandra#291]
I'm just getting started with v2 of locp/cassandra and am confused by this example which appears to declare ::cassandra with both the new and old api?

https://github.com/locp/cassandra/blob/master/README.md#beginning-with-cassandra

Is that just an error left over from older doc?

**Comment by dallinb** [comment]
@ericy-jana 

Thank you for bringing this to my attention.  It is indeed left over from the older documentation.  I'll get a patch out as soon as possible.  That's the trouble with writing open source at the end of a long day.

Ben

**Comment by ericy-jana** [comment]
Thanks @dallinb!  Nice job with 2.0.  I really like being able to fully describe casssandra.yaml in Hiera.

**Comment by dallinb** [comment]
Thanks again for the heads up.  The fix is scheduled for v2.0.2.
