### ISSUE TITLE
Bundle Failing to Install on Ruby 2.1.5 and Puppet 3.8.4

### ISSUE THREAD

**Issue by dallinb** [locp/cassandra#302]
https://travis-ci.org/locp/cassandra/jobs/170743765

This is not customer impacting so does not require a hotfix.

**Comment by tibers** [comment]
Puppet 3.8.x + Ruby 2.1.x isn't supported-ish: https://docs.puppet.com/puppet/3.8/reference/system_requirements.html#ruby

**Comment by dallinb** [comment]
@tibers 

Thanks for the note.  Made me take a look at the support matrix for puppetlabs-ntp and now back on course.
