### ISSUE TITLE
Unable to configure empty numeric values

### ISSUE THREAD

**Issue by lemkep** [locp/cassandra#380]
Hi, thanks for your nice cassandra module. 
If I configure it like at
https://github.com/locp/cassandra/wiki/Suggested-Baseline-Settings for numerical values eg.
```
    class { 'cassandra':
      baseline_settings => {
        ...
        'counter_cache_size_in_mb'                 => '',
        ...
      },
    ...
```
`@merged_hash.to_yaml()` from `cassandra.yaml.erb` formats it to 
`counter_cache_size_in_mb: ''` in `cassandra.yaml` and cassandra complains with
```
Caused by: org.yaml.snakeyaml.constructor.ConstructorException: null; Can't construct a java object for tag:yaml.org,2002:org.apache.cassandra.config.Config; exception=Cannot create property=counter_cache_size_in_mb for JavaBean=org.apache.cassandra.config.Config@17695df3; String index out of range: 0;  in 'reader', line 6, column 1
```
Environment:
- Debian Jessie (node and master)
- cassandra 3.0.12
- puppet 4

I tried to set empty values by different means, but found the only way is with an explicit template entry. Or remove this settings completely as empty is default.

**Comment by dallinb** [comment]
Will test the code again and especially against your configuration and get back to you.

**Comment by dallinb** [comment]
Sure enough, the same is also true for `index_summary_capacity_in_mb` and `key_cache_size_in_mb`.  I'll remove those entries from the Wiki.  I'm also working on incorporating this as am acceptance test in future releases as well.

**Comment by dallinb** [comment]
It seems that when setting up the hieradata for this in the past (see https://github.com/locp/cassandra/blob/2.4.0/spec/acceptance/hieradata/environments/production/data/common.yaml) this problem must have been discovered but had never made it into the documentation in the Wiki.  Thanks again to @lemkep for raising this to our attention!
