### ISSUE TITLE
Fails To Run With puppetlabs-apt v1.8.0

### ISSUE THREAD

**Issue by DylanGriffith** [locp/cassandra#87]
I get an error about the use of `apt::key` using invalid params. I updated the `apt::key` stuff locally but still had problems with `apt::source`. I just think it's incompatible with `1.8.0` but the dependencies seem to suggest it is.

```
Error: Invalid parameter include on Apt::Source[datastax] at   modules/cassandra/manifests/datastax_repo.pp:35 on node
Wrapped exception:
Invalid parameter include
```

**Comment by DylanGriffith** [comment]
These were the changes I had to make to get it to work:

https://github.com/locp/cassandra/compare/master...dgvz:apt-1.8-compatible

**Comment by dallinb** [comment]
Hi Dylan,

Thank you very much for identifying this.  Your code is also far more elegant so I will go ahead and use it.  Will get another release out within the next 24 hours.

Best wishes,

Ben

**Comment by dallinb** [comment]
Hi,

Looking at this closer.  It is because the `key` and `key_source` parameters were deprecated in `apt::key` and the `include_src` was deprecated in `apt::source` when the module got to >= 2.0.0.  I think this is probably more a problem with my dependencies and I need to update apt to be >= 2.0.0.  Do you have any problem with an updated version of apt?

**Comment by DylanGriffith** [comment]
Thanks for looking into it.

Yeah they changed the API to apt. It's not really feasible for us to upgrade apt though so will probably have to use our fork. The only other approach I can think of is some kind of puppety way of handling both by checking which version is being used. Not really sure though if that would be too ugly.

**Comment by dallinb** [comment]
Hi Dylan,

I've taken a look to see if there was a handy version string in the apt module that I could use.  Unfortunately not.  As far as the deprecated parameters are concerned, they would work with the current version of apt.  It's just you would receive a lot of deprecation warnings when your manifest was executing.  Of course you may also have other dependencies that could break your manifest.  Sorry for the aggravation.

**Comment by DylanGriffith** [comment]
No worries. I really appreciate you looking into that much detail. I didn't realise they were still supporting the old params as deprecated. I might be able to upgrade after all. Thanks again.
