### ISSUE TITLE
service_ensure unused

### ISSUE THREAD

**Issue by sampowers** [locp/cassandra#93]
The way this is right now it seems like it'd not be possible to use service_ensure to control the service state.

https://github.com/locp/cassandra/blob/master/manifests/init.pp#L110

**Comment by dallinb** [comment]
Sam,

Thank you for spotting that rather embarrassing oversight and for fixing it.  I'll get that deployed to the forge (with an acknowledgement of your work) within the next 24 hours.

Best wishes and thanks again,

Ben
